version: '3'
services:
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - 5000:5000
    environment:
      - MONGO_HOST=cluster0.ota7y4c.mongodb.net
      - MONGO_PORT=27017
      - MONGO_USERNAME=shashwat79802
      - MONGO_PASSWORD=shashwat79802
      - MONGO_DATABASE=test
